### ISSUE TITLE
gqlgen behavior doesn't match the tutorial

### ISSUE THREAD

**Issue by zellyn** [vektah/gqlgen-tutorials#2]
Thanks for the lovely package and surprisingly good documentation. I've been avidly reading your docs and the graphql docs, and I have a problem working through the tutorials:

In the [Generate the Bindings section of the tutorial](https://gqlgen.com/getting-started#generate-the-bindings), it claims that the generated models will look like:

```go
type Todo struct {
	ID     string
	Text   string
	Done   bool
	UserID string
}

type User struct {
	ID   string
	Name string
}
```

but when I run `gqlgen` myself on the tutorial schema, I get:

```go
type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User User   `json:"user"`
}
type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
```

The important part is that the `User` struct is included in the `Todo` struct, rather than just a `UserID`, which leaves me (a) wondering how I avoid populating the whole `User` object on a `Todo` if it wasn't queried, and (b) wondering how the `dataloader` tutorial matches up with reality, if all the object references are different.

(Obviously, in the tutorial, populating the whole `User` object is no harder than returning the `UserID`, but of course my real objective is to use `gqlgen` with a more complex schema.)

**Comment by vektah** [comment]
Sorry I didn't see this earlier. Both the getting started guide and this repo have been updated for 0.11.

In particular, [this section](https://gqlgen.com/getting-started/#dont-eagarly-fetch-the-user) talks about how to avoid this behaviour.
